### ISSUE TITLE
STILL OPEN [1.16.5] java.nio.file.NoSuchFileException: titanium.toml | Forge Modded Instance Crashes On Startup

### ISSUE THREAD

**Issue by Jessman5** [InnovativeOnlineIndustries/Titanium#97]
Hej there. 
So as soon as I put Titatium (latest version + whatever version before) in my forge modded Modpack to be able to put in Industrial Foregoing, the game crashes at startup. That happens for a long while now, thus with multiple versions.

I play via ATLauncher on a Mac, if this info helps.

**Titanium Version: **
latest few ones

**Crashlog If Applicable (Upload to pastebin/gist): **
---- Minecraft Crash Report ----
// Oops.

Time: 8/29/21 11:25 AM
Description: Rendering overlay

com.electronwill.nightconfig.core.io.WritingException: An I/O error occured
	at com.electronwill.nightconfig.core.io.ConfigParser.parse(ConfigParser.java:222) ~[core-3.6.3.jar:?] {}
	at com.electronwill.nightconfig.core.io.ConfigParser.parse(ConfigParser.java:202) ~[core-3.6.3.jar:?] {}
	at com.electronwill.nightconfig.core.file.WriteSyncFileConfig.load(WriteSyncFileConfig.java:73) ~[core-3.6.3.jar:?] {}
	at com.electronwill.nightconfig.core.file.AutosaveCommentedFileConfig.load(AutosaveCommentedFileConfig.java:85) ~[core-3.6.3.jar:?] {}
	at net.minecraftforge.fml.config.ConfigFileTypeHandler.lambda$reader$1(ConfigFileTypeHandler.java:57) ~[?:?] {re:classloading}
	at net.minecraftforge.fml.config.ConfigTracker.openConfig(ConfigTracker.java:104) ~[?:?] {re:classloading}
	at net.minecraftforge.fml.config.ConfigTracker.lambda$loadConfigs$1(ConfigTracker.java:83) ~[?:?] {re:classloading}
	at java.lang.Iterable.forEach(Iterable.java:75) ~[?:1.8.0_74] {}
	at java.util.Collections$SynchronizedCollection.forEach(Collections.java:2062) ~[?:1.8.0_74] {}
	at net.minecraftforge.fml.config.ConfigTracker.loadConfigs(ConfigTracker.java:83) ~[?:?] {re:classloading}
	at net.minecraftforge.fml.ModLoader.loadMods(ModLoader.java:209) ~[?:?] {re:classloading}
	at net.minecraftforge.fml.client.ClientModLoader.lambda$startModLoading$7(ClientModLoader.java:132) ~[?:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraftforge.fml.client.ClientModLoader.lambda$createRunnableWithCatch$4(ClientModLoader.java:123) ~[?:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraftforge.fml.client.ClientModLoader.startModLoading(ClientModLoader.java:132) ~[?:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraftforge.fml.client.ClientModLoader.lambda$onResourceReload$2(ClientModLoader.java:114) ~[?:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraftforge.fml.client.ClientModLoader.lambda$createRunnableWithCatch$4(ClientModLoader.java:123) ~[?:?] {re:classloading,pl:runtimedistcleaner:A}
	at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1626) ~[?:1.8.0_74] {}
	at java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1618) ~[?:1.8.0_74] {}
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289) ~[?:1.8.0_74] {}
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056) ~[?:1.8.0_74] {}
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692) ~[?:1.8.0_74] {}
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157) ~[?:1.8.0_74] {}
Caused by: java.nio.file.NoSuchFileException: /Applications/ATLauncher.app/Contents/Java/instances/11652VanillaMinecraftForge/config/titanium/titanium.toml
	at sun.nio.fs.UnixException.translateToIOException(UnixException.java:86) ~[?:1.8.0_74] {}
	at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:102) ~[?:1.8.0_74] {}
	at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:107) ~[?:1.8.0_74] {}
	at sun.nio.fs.UnixFileSystemProvider.newByteChannel(UnixFileSystemProvider.java:214) ~[?:1.8.0_74] {}
	at java.nio.file.Files.newByteChannel(Files.java:361) ~[?:1.8.0_74] {}
	at java.nio.file.Files.createFile(Files.java:632) ~[?:1.8.0_74] {}
	at net.minecraftforge.fml.config.ConfigFileTypeHandler.setupConfigFile(ConfigFileTypeHandler.java:89) ~[?:?] {re:classloading}
	at net.minecraftforge.fml.config.ConfigFileTypeHandler.lambda$null$0(ConfigFileTypeHandler.java:51) ~[?:?] {re:classloading}
	at com.electronwill.nightconfig.core.io.ConfigParser.parse(ConfigParser.java:215) ~[core-3.6.3.jar:?] {}
	... 21 more

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at com.electronwill.nightconfig.core.io.ConfigParser.parse(ConfigParser.java:222) ~[core-3.6.3.jar:?] {}
	at com.electronwill.nightconfig.core.io.ConfigParser.parse(ConfigParser.java:202) ~[core-3.6.3.jar:?] {}
	at com.electronwill.nightconfig.core.file.WriteSyncFileConfig.load(WriteSyncFileConfig.java:73) ~[core-3.6.3.jar:?] {}
	at com.electronwill.nightconfig.core.file.AutosaveCommentedFileConfig.load(AutosaveCommentedFileConfig.java:85) ~[core-3.6.3.jar:?] {}
	at net.minecraftforge.fml.config.ConfigFileTypeHandler.lambda$reader$1(ConfigFileTypeHandler.java:57) ~[?:?] {re:classloading}
	at net.minecraftforge.fml.config.ConfigTracker.openConfig(ConfigTracker.java:104) ~[?:?] {re:classloading}
	at net.minecraftforge.fml.config.ConfigTracker.lambda$loadConfigs$1(ConfigTracker.java:83) ~[?:?] {re:classloading}
	at java.lang.Iterable.forEach(Iterable.java:75) ~[?:1.8.0_74] {}
-- Overlay render details --
Details:
	Overlay name: net.minecraft.client.gui.ResourceLoadProgressGui
Stacktrace:
	at net.minecraft.client.renderer.GameRenderer.func_195458_a(GameRenderer.java:484) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,xf:fml:fairylights:GameRendererTransformer,pl:mixin:APP:flywheel.mixins.json:StoreProjectionMatrixMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.func_195542_b(Minecraft.java:976) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:mining_helmet.mixins.json:MinecraftMixin,pl:mixin:APP:immersiveengineering.mixins.json:accessors.client.MinecraftAccess,pl:mixin:APP:flywheel.mixins.json:ShaderCloseMixin,pl:mixin:APP:create.mixins.json:WindowResizeMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:607) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:mining_helmet.mixins.json:MinecraftMixin,pl:mixin:APP:immersiveengineering.mixins.json:accessors.client.MinecraftAccess,pl:mixin:APP:flywheel.mixins.json:ShaderCloseMixin,pl:mixin:APP:create.mixins.json:WindowResizeMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.main(Main.java:184) ~[client-1.16.5.jar:?] {re:classloading,pl:runtimedistcleaner:A}
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_74] {}
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_74] {}
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_74] {}
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_74] {}
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:51) ~[forge-1.16.5-36.2.2.jar:36.2] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-8.0.9.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54) [modlauncher-8.0.9.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72) [modlauncher-8.0.9.jar:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:82) [modlauncher-8.0.9.jar:?] {}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:66) [modlauncher-8.0.9.jar:?] {}

-- System Details --
Details:
	Minecraft Version: 1.16.5
	Minecraft Version ID: 1.16.5
	Operating System: Mac OS X (x86_64) version 10.16
	Java Version: 1.8.0_74, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 2455527168 bytes (2341 MB) / 4294967296 bytes (4096 MB) up to 4294967296 bytes (4096 MB)
	CPUs: 4
	JVM Flags: 12 total; -XX:-OmitStackTraceInFastThrow -Xms512M -Xmx4096M -XX:MetaspaceSize=256M -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M -Xss1M -XX:+IgnoreUnrecognizedVMOptions
	ModLauncher: 8.0.9+86+master.3cf110c
	ModLauncher launch target: fmlclient
	ModLauncher naming: srg
	ModLauncher services: 
		/mixin-0.8.2.jar mixin PLUGINSERVICE 
		/eventbus-4.0.0.jar eventbus PLUGINSERVICE 
		/forge-1.16.5-36.2.2.jar object_holder_definalize PLUGINSERVICE 
		/forge-1.16.5-36.2.2.jar runtime_enum_extender PLUGINSERVICE 
		/accesstransformers-3.0.1.jar accesstransformer PLUGINSERVICE 
		/forge-1.16.5-36.2.2.jar capability_inject_definalize PLUGINSERVICE 
		/forge-1.16.5-36.2.2.jar runtimedistcleaner PLUGINSERVICE 
		/mixin-0.8.2.jar mixin TRANSFORMATIONSERVICE 
		/forge-1.16.5-36.2.2.jar fml TRANSFORMATIONSERVICE 
	FML: 36.2
	Forge: net.minecraftforge:36.2.2
	FML Language Providers: 
		javafml@36.2
		minecraft@1
	Mod List: 
		create-stuff-additions1.16.5_v1.0.6.jar           |Create Stuff Additions        |create_stuff_additions        |1.0.6               |COMMON_SET|Manifest: NOSIGNATURE
		ClientTweaks_1.16.3-5.3.0.jar                     |Client Tweaks                 |clienttweaks                  |5.3.0               |COMMON_SET|Manifest: NOSIGNATURE
		NetherPortalFix_1.16.3-7.2.1.jar                  |NetherPortalFix               |netherportalfix               |7.2.1               |COMMON_SET|Manifest: NOSIGNATURE
		pamhc2trees-1.16.3-1.0.0.jar                      |Pam's HarvestCraft 2 Fruit Tre|pamhc2trees                   |1.0.0               |COMMON_SET|Manifest: NOSIGNATURE
		mining-helmet-1.16.4-2.0.0.jar                    |Mining Helmet                 |mining_helmet                 |2.0.0               |COMMON_SET|Manifest: NOSIGNATURE
		morecreatestuffs-mc1.16-1.4.1a.jar                |More Create Stuffs            |morecreatestuffs              |mc1.16-1.4.1        |COMMON_SET|Manifest: NOSIGNATURE
		craftingstation-4.1.1.jar                         |Crafting Station              |craftingstation               |4.1.1               |COMMON_SET|Manifest: NOSIGNATURE
		jei-1.16.5-7.7.1.118.jar                          |Just Enough Items             |jei                           |7.7.1.118           |COMMON_SET|Manifest: NOSIGNATURE
		WildFarmCraft.jar                                 |WildFarmCraft                 |wildfarmcraft                 |1.0.0               |COMMON_SET|Manifest: NOSIGNATURE
		Mekanism-1.16.5-10.0.21.448.jar                   |Mekanism                      |mekanism                      |10.0.21             |COMMON_SET|Manifest: NOSIGNATURE
		mcw-windows-1.0.3-mc1.16.5.jar                    |Macaw's Windows               |mcwwindows                    |1.0.3               |COMMON_SET|Manifest: NOSIGNATURE
		ropebridge-1.16.4-2.1.jar                         |Rope Bridge                   |ropebridge                    |1.16.4-2.1          |COMMON_SET|Manifest: NOSIGNATURE
		rsgauges-1.16.4-1.2.9-b1.jar                      |Gauges and Switches           |rsgauges                      |1.2.9-b1            |COMMON_SET|Manifest: bf:30:76:97:e4:58:41:61:2a:f4:30:d3:8f:4c:e3:71:1d:14:c4:a1:4e:85:36:e3:1d:aa:2f:cb:22:b0:04:9b
		invtweaks-1.16.4-1.0.1.jar                        |Inventory Tweaks Renewed      |invtweaks                     |1.16.4-1.0.1        |COMMON_SET|Manifest: NOSIGNATURE
		Neat 1.7-27.jar                                   |Neat                          |neat                          |1.7-27              |COMMON_SET|Manifest: NOSIGNATURE
		createchunkloading-0.2.0.jar                      |Create Chunkloading           |createchunkloading            |0.2.0               |COMMON_SET|Manifest: NOSIGNATURE
		jev-1.16.3-2.0.1.jar                              |Just Enough Vehicles          |jev                           |2.0.1               |COMMON_SET|Manifest: NOSIGNATURE
		ForgeEndertech-1.16.4-7.0.10.0-build.0037.jar     |Forge Endertech               |forgeendertech                |7.0.10.0            |COMMON_SET|Manifest: NOSIGNATURE
		journeymap-1.16.5-5.7.3.jar                       |Journeymap                    |journeymap                    |5.7.3               |COMMON_SET|Manifest: NOSIGNATURE
		comforts-forge-1.16.4-4.0.1.0.jar                 |Comforts                      |comforts                      |1.16.4-4.0.1.0      |COMMON_SET|Manifest: NOSIGNATURE
		appliedenergistics2-8.4.0.jar                     |Applied Energistics 2         |appliedenergistics2           |8.4.0               |COMMON_SET|Manifest: 95:58:cc:83:9d:a8:fa:4f:e9:f3:54:90:66:61:c8:ae:9c:08:88:11:52:52:df:2d:28:5f:05:d8:28:57:0f:98
		SereneSeasons-1.16.5-4.0.1.91-universal.jar       |Serene Seasons                |sereneseasons                 |1.16.5-4.0.1.91     |COMMON_SET|Manifest: NOSIGNATURE
		Powah-1.16.5-2.3.16.jar                           |Powah                         |powah                         |2.3.16              |COMMON_SET|Manifest: NOSIGNATURE
		mightyarchitect-mc1.16.3_v0.5.jar                 |The Mighty Architect          |mightyarchitect               |0.5                 |COMMON_SET|Manifest: NOSIGNATURE
		Bookshelf-1.16.5-10.0.6.jar                       |Bookshelf                     |bookshelf                     |10.0.6              |COMMON_SET|Manifest: eb:c4:b1:67:8b:f9:0c:db:dc:4f:01:b1:8e:61:64:39:4c:10:85:0b:a6:c4:c7:48:f0:fa:95:f2:cb:08:3a:e5
		u_team_core-1.16.5-3.2.0.193.jar                  |U Team Core                   |uteamcore                     |3.2.0.193           |COMMON_SET|Manifest: f4:a6:0b:ee:cb:8a:1a:ea:9f:9d:45:91:8f:8b:b3:ae:26:f3:bf:05:86:1d:90:9e:f6:32:2a:1a:ed:1d:ce:b0
		buildinggadgets-1.16.5-3.8.0.jar                  |Building Gadgets              |buildinggadgets               |3.8.0               |COMMON_SET|Manifest: NOSIGNATURE
		mcjtylib-1.16-5.0.19.jar                          |McJtyLib                      |mcjtylib                      |1.16-5.0.19         |COMMON_SET|Manifest: NOSIGNATURE
		rftoolsbase-1.16-2.0.10.jar                       |RFToolsBase                   |rftoolsbase                   |1.16-2.0.10         |COMMON_SET|Manifest: NOSIGNATURE
		xnet-1.16-3.0.11.jar                              |XNet                          |xnet                          |1.16-3.0.11         |COMMON_SET|Manifest: NOSIGNATURE
		DarkUtilities-1.16.5-8.0.10.jar                   |Dark Utilities                |darkutils                     |8.0.10              |COMMON_SET|Manifest: eb:c4:b1:67:8b:f9:0c:db:dc:4f:01:b1:8e:61:64:39:4c:10:85:0b:a6:c4:c7:48:f0:fa:95:f2:cb:08:3a:e5
		mcw-doors-1.0.2-mc1.16.5.jar                      |Macaw's Doors                 |mcwdoors                      |1.0.2               |COMMON_SET|Manifest: NOSIGNATURE
		MekanismGenerators-1.16.5-10.0.21.448.jar         |Mekanism: Generators          |mekanismgenerators            |10.0.21             |COMMON_SET|Manifest: NOSIGNATURE
		Hwyla-forge-1.10.11-B78_1.16.2.jar                |Waila                         |waila                         |1.10.11-B78_1.16.2  |COMMON_SET|Manifest: NOSIGNATURE
		WAWLA-1.16.5-8.0.2.jar                            |WAWLA                         |wawla                         |8.0.2               |COMMON_SET|Manifest: eb:c4:b1:67:8b:f9:0c:db:dc:4f:01:b1:8e:61:64:39:4c:10:85:0b:a6:c4:c7:48:f0:fa:95:f2:cb:08:3a:e5
		TMechworks-1.16.3+-2.2.5.jar                      |Tinkers' Mechworks            |tmechworks                    |2.2.5               |COMMON_SET|Manifest: NOSIGNATURE
		JustEnoughResources-1.16.5-0.12.1.127.jar         |Just Enough Resources         |jeresources                   |0.12.1.127          |COMMON_SET|Manifest: NOSIGNATURE
		rftoolspower-1.16-3.0.8.jar                       |RFToolsPower                  |rftoolspower                  |1.16-3.0.8          |COMMON_SET|Manifest: NOSIGNATURE
		forge-1.16.5-36.2.2-universal.jar                 |Forge                         |forge                         |36.2.2              |COMMON_SET|Manifest: 22:af:21:d8:19:82:7f:93:94:fe:2b:ac:b7:e4:41:57:68:39:87:b1:a7:5c:c6:44:f9:25:74:21:14:f5:0d:90
		Terridus_1.16.5_V3.1.jar                          |terridus                      |terridus                      |1.0.0               |COMMON_SET|Manifest: NOSIGNATURE
		refinedstorage-1.9.12.jar                         |Refined Storage               |refinedstorage                |1.9.12              |COMMON_SET|Manifest: NOSIGNATURE
		GamemodeOverhaul-1.16.4-1.4.2.4.jar               |GamemodeOverhaul              |gamemodeoverhaul              |1.16.4-1.4.2.4      |COMMON_SET|Manifest: NOSIGNATURE
		ironchest-1.16.4-11.2.10.jar                      |Iron Chests                   |ironchest                     |1.16.4-11.2.10      |COMMON_SET|Manifest: NOSIGNATURE
		CraftingTweaks_1.16.5-12.2.1.jar                  |Crafting Tweaks               |craftingtweaks                |12.2.1              |COMMON_SET|Manifest: NOSIGNATURE
		forge-1.16.5-36.2.2-client.jar                    |Minecraft                     |minecraft                     |1.16.5              |COMMON_SET|Manifest: NOSIGNATURE
		cofh_core-1.16.3-1.1.6.jar                        |CoFH Core                     |cofh_core                     |1.1.6               |COMMON_SET|Manifest: NOSIGNATURE
		thermal_foundation-1.16.3-1.1.6.jar               |Thermal Series                |thermal                       |1.1.6               |COMMON_SET|Manifest: NOSIGNATURE
		TConstruct-1.16.5-3.1.2.265.jar                   |Tinkers' Construct            |tconstruct                    |3.1.2.265           |COMMON_SET|Manifest: NOSIGNATURE
		mcw-bridges-1.0.6-mc1.16.5.jar                    |Macaw's Bridges               |mcwbridges                    |1.0.6               |COMMON_SET|Manifest: NOSIGNATURE
		industrial-foregoing-1.16.5-3.2.14.5-13.jar       |Industrial Foregoing          |industrialforegoing           |3.2.14.5            |COMMON_SET|Manifest: NOSIGNATURE
		useful_backpacks-1.16.5-1.12.0.88.jar             |Useful Backpacks              |usefulbackpacks               |1.12.0.88           |COMMON_SET|Manifest: f4:a6:0b:ee:cb:8a:1a:ea:9f:9d:45:91:8f:8b:b3:ae:26:f3:bf:05:86:1d:90:9e:f6:32:2a:1a:ed:1d:ce:b0
		thermal_innovation-1.16.3-1.1.7.jar               |Thermal Innovation            |thermal_innovation            |1.1.7               |COMMON_SET|Manifest: NOSIGNATURE
		MouseTweaks-2.14-mc1.16.2.jar                     |Mouse Tweaks                  |mousetweaks                   |2.14                |COMMON_SET|Manifest: NOSIGNATURE
		titanium-1.16.5-3.2.8.5-19.jar                    |Titanium                      |titanium                      |3.2.8.5             |COMMON_SET|Manifest: NOSIGNATURE
		ImmersiveEngineering-1.16.5-5.0.3-138.jar         |Immersive Engineering         |immersiveengineering          |1.16.5-5.0.3-138    |COMMON_SET|Manifest: 44:39:94:cf:1d:8c:be:3c:7f:a9:ee:f4:1e:63:a5:ac:61:f9:c2:87:d5:5b:d9:d6:8c:b5:3e:96:5d:8e:3f:b7
		BiomesOPlenty-1.16.5-13.1.0.482-universal.jar     |Biomes O' Plenty              |biomesoplenty                 |1.16.5-13.1.0.482   |COMMON_SET|Manifest: NOSIGNATURE
		Lollipop-1.16.5-3.2.9.jar                         |Lollipop                      |lollipop                      |3.2.9               |COMMON_SET|Manifest: NOSIGNATURE
		pamhc2crops-1.16.3-1.0.1.jar                      |Pam's HarvestCraft 2 Crops    |pamhc2crops                   |version             |COMMON_SET|Manifest: NOSIGNATURE
		AdLods-1.16.4-4.1.4.0-build.0043.jar              |Large Ore Deposits            |adlods                        |4.1.4.0             |COMMON_SET|Manifest: NOSIGNATURE
		fairylights-4.0.5-1.16.5.jar                      |Fairy Lights                  |fairylights                   |4.0.5               |COMMON_SET|Manifest: NOSIGNATURE
		astikorcarts-1.16.5-1.1.1.jar                     |AstikorCarts                  |astikorcarts                  |1.1.1               |COMMON_SET|Manifest: NOSIGNATURE
		pamhc2foodextended-1.16.3-1.0.1.jar               |Pam's HarvestCraft 2 Food Exte|pamhc2foodextended            |version             |COMMON_SET|Manifest: NOSIGNATURE
		car-1.16.5-1.0.4.jar                              |Ultimate Car Mod              |car                           |1.16.5-1.0.4        |COMMON_SET|Manifest: NOSIGNATURE
		jeiintegration_1.16.5-7.0.1.15.jar                |JEI Integration               |jeiintegration                |7.0.1.15            |COMMON_SET|Manifest: NOSIGNATURE
		flywheel-1.16-0.2.3.jar                           |Flywheel                      |flywheel                      |1.16-0.2.3          |COMMON_SET|Manifest: NOSIGNATURE
		create-mc1.16.5_v0.3.2d.jar                       |Create                        |create                        |v0.3.2d             |COMMON_SET|Manifest: NOSIGNATURE
		createautomated-1.16.5-1.2.1b.jar                 |Create Automated              |createautomated               |1.16.5-1.2.1b       |COMMON_SET|Manifest: NOSIGNATURE
		creategears-1.16.5-1.3.1.jar                      |Create Gears                  |creategears                   |1.16.5-1.3.1        |COMMON_SET|Manifest: NOSIGNATURE
		Patchouli-1.16.4-50.jar                           |Patchouli                     |patchouli                     |1.16.4-50           |COMMON_SET|Manifest: NOSIGNATURE
		Mantle-1.16.5-1.6.123.jar                         |Mantle                        |mantle                        |1.6.123             |COMMON_SET|Manifest: NOSIGNATURE
		pamhc2foodcore-1.16.3-1.0.2.jar                   |Pam's HarvestCraft 2 Food Core|pamhc2foodcore                |version             |COMMON_SET|Manifest: NOSIGNATURE
		thermal_cultivation-1.16.3-1.1.6.jar              |Thermal Cultivation           |thermal_cultivation           |1.1.6               |COMMON_SET|Manifest: NOSIGNATURE
		polymorph-forge-1.16.5-0.24.jar                   |Polymorph                     |polymorph                     |1.16.5-0.24         |COMMON_SET|Manifest: NOSIGNATURE
		enderioalloys-1.16.5-1.0.2.jar                    |EnderIO Alloys                |enderioalloys                 |1.16.5-1.0.2        |COMMON_SET|Manifest: NOSIGNATURE
		thermal_expansion-1.16.3-1.1.6.jar                |Thermal Expansion             |thermal_expansion             |1.1.6               |COMMON_SET|Manifest: NOSIGNATURE
		ftb-ultimine-forge-1605.3.0-build.21.jar          |FTB Ultimine                  |ftbultimine                   |1605.3.0-build.21   |COMMON_SET|Manifest: NOSIGNATURE
		obfuscate-0.6.2-1.16.3.jar                        |Obfuscate                     |obfuscate                     |0.6.2               |COMMON_SET|Manifest: e1:59:1a:56:ec:97:b3:d0:b3:4b:25:06:1f:83:b0:f4:fd:0c:24:e3:6d:ea:94:b1:9f:22:b0:38:13:60:88:ea
		vehicle-mod-0.45.2-1.16.3.jar                     |MrCrayfish's Vehicle Mod      |vehicle                       |0.45.2              |COMMON_SET|Manifest: NOSIGNATURE
		structurize-0.13.156-ALPHA-universal.jar          |Structurize                   |structurize                   |0.13.156-ALPHA      |COMMON_SET|Manifest: NOSIGNATURE
		Runelic-1.16.5-7.0.1.jar                          |Runelic                       |runelic                       |7.0.1               |COMMON_SET|Manifest: eb:c4:b1:67:8b:f9:0c:db:dc:4f:01:b1:8e:61:64:39:4c:10:85:0b:a6:c4:c7:48:f0:fa:95:f2:cb:08:3a:e5
		worldedit-mod-7.2.5-dist.jar                      |WorldEdit                     |worldedit                     |7.2.5+57d5ac9       |COMMON_SET|Manifest: NOSIGNATURE
		cavebiomeapi-1.16.5-1.3.1.jar                     |CaveBiomeAPI                  |cavebiomeapi                  |1.3.1               |COMMON_SET|Manifest: NOSIGNATURE
		MekanismTools-1.16.5-10.0.21.448.jar              |Mekanism: Tools               |mekanismtools                 |10.0.21             |COMMON_SET|Manifest: NOSIGNATURE
		architectury-1.20.28-forge.jar                    |Architectury                  |architectury                  |1.20.28             |COMMON_SET|Manifest: NOSIGNATURE
		ftb-library-forge-1605.3.1-build.48.jar           |FTB Library                   |ftblibrary                    |1605.3.1-build.48   |COMMON_SET|Manifest: NOSIGNATURE
		refinedstorageaddons-0.7.3.jar                    |Refined Storage Addons        |refinedstorageaddons          |0.7.3               |COMMON_SET|Manifest: NOSIGNATURE
		CAC+MOD+[1.16.5]+[2021.2-pre4].jar                |Caves And Cliffs mod [1.16.4] |caves_and_cliffs_mod          |MOD                 |COMMON_SET|Manifest: NOSIGNATURE
		FastLeafDecay-v25.jar                             |FastLeafDecay                 |fastleafdecay                 |v25                 |COMMON_SET|Manifest: NOSIGNATURE
		DynamicTrees-1.16.5-0.10.0-Beta24.jar             |Dynamic Trees                 |dynamictrees                  |1.16.5-0.10.0-Beta24|COMMON_SET|Manifest: NOSIGNATURE
		DynamicTreesPlus-1.16.5-0.1.0-Beta10.jar          |Dynamic Trees Plus            |dynamictreesplus              |1.16.5-0.1.0-Beta10 |COMMON_SET|Manifest: NOSIGNATURE
		DynamicTreesBOP-1.16.5-2.0.6.jar                  |Dynamic Trees for Biomes o' Pl|dtbop                         |1.16.5-2.0.6        |COMMON_SET|Manifest: NOSIGNATURE
		chiselsandbits-0.3.4-RELEASE.jar                  |Chisels & bits                |chiselsandbits                |NONE                |COMMON_SET|Manifest: NOSIGNATURE
		WailaHarvestability-mc1.16.x-forge-1.1.15.jar     |Waila Harvestability          |wailaharvestability           |1.1.15              |COMMON_SET|Manifest: NOSIGNATURE
		Fast+Gamemode+Switch+1.16.4+-+1.2.jar             |Fast Gamemode Switch Mod      |fastgamemodeswitchmod         |1.0.0               |COMMON_SET|Manifest: NOSIGNATURE
		createaddition-1.16.5-20210810a.jar               |Create Crafts & Additions     |createaddition                |1.16.5-20210810a    |COMMON_SET|Manifest: NOSIGNATURE
		BetterAdvancements-1.16.5-0.1.0.105.jar           |Better Advancements           |betteradvancements            |0.1.0.105           |COMMON_SET|Manifest: NOSIGNATURE
	Crash Report UUID: a8854b35-270a-45a8-933a-11dae07c8246
	Launched Version: 1.16.5

**Comment by Buuz135** [comment]
Delete titanium's config file it might help, it might be another mod causing this

**Comment by Jessman5** [comment]
Did that. Didn't help.

**Comment by Buuz135** [comment]
Does it happen if you remove titanium and IF now?

**Comment by Jessman5** [comment]
Still crashes.
So actually this issue is still open. Don't know why you've closed it so fast.
